### ISSUE TITLE
能添加功能：上传文件时，可以通过MinerU处理和导入到MemoRAG吗？

### ISSUE THREAD

**Issue by tqangxl** [qhjqhj00/MemoRAG#11]
能添加功能：上传文件时，可以通过MinerU处理和导入到MemoRAG吗
MinerU：
https://github.com/opendatalab/MinerU/releases

再或者VL模型分析提取内容，再存入MemoRAG？
https://www.modelscope.cn/models/qwen/Qwen2-VL-7B-Instruct-GPTQ-Int8

 所以checkpoint 加载时， 允许 `qwen2_vl` ，允许 Transformers 和Mamba  architecture的 checkpoint,

**Comment by qhjqhj00** [comment]
非常感谢您的关注和建议，我们正在讨论MemoRAG的开发安排，会将您的建议列入讨论！
