### ISSUE TITLE
同一文件，多次修改内容并提交上传MemoRAG，内容实时更新和删除的问题

### ISSUE THREAD

**Issue by tqangxl** [qhjqhj00/MemoRAG#12]
同一文件，多次修改内容并提交上传MemoRAG，内容实时更新和删除的问题

**Comment by qhjqhj00** [comment]
非常感谢您的关注和建议，目前如果对context进行修改，需要重新生成memory cache。您的建议在当前MemoRAG框架中实现起来比较复杂。我们在未来开发计划中有涉及memory的update的部分，将会积极参考您的建议！
