### ISSUE TITLE
How does this pipe.memorize work specifically? Load this text into the model for pre training, and then store the trained weights in memory

### ISSUE THREAD

**Issue by abc-w** [qhjqhj00/MemoRAG#14]
pipe.memorize(small_part, save_dir="content/harry_potter/", print_stats=True)
How does this work specifically? Load this small_part text into the model for pre training, and then store the trained weights in memory

**Comment by qhjqhj00** [comment]
After calling pipe.memorize(), the memory model encodes the entire input context into a compressed KV cache. The input context is then chunked into passages, which are indexed using the retriever’s encoder. For further details, please refer to our Technical Report.

**Comment by LiuXiaoxuanPKU** [comment]
> After calling pipe.memorize(), the memory model encodes the entire input context into a compressed KV cache. The input context is then chunked into passages, which are indexed using the retriever’s encoder. For further details, please refer to our Technical Report.

Could you point out the code in [memorag.py](https://github.com/qhjqhj00/MemoRAG/blob/main/memorag/memorag.py) where memory is used? Thanks.
