### ISSUE TITLE
How are the memory tokens obtained?

### ISSUE THREAD

**Issue by WenjinW** [qhjqhj00/MemoRAG#15]
MemoRAG is an inspiring piece of work. Thank you for your contribution to the community.
While reading the technical report, I encountered the following issues:

1. How to get the memory tokens at the begin in formula (5)：
![image](https://github.com/user-attachments/assets/e9a69481-780e-42e6-98e2-294317bdab87)

2. How to construct the train data for formula (8)：
![image](https://github.com/user-attachments/assets/63754084-9cdb-42bf-82c8-93514d8164b6)

I believe the training method used in MemoRAG is crucial for understanding this work. Could you provide more details?

Looking forward to your response, thank you.

**Comment by qhjqhj00** [comment]
Thank you for your interest in our work. We will release the training code and data as soon as possible. I believe both of your questions will be addressed once they are available.
