### ISSUE TITLE
【提问】工作解决的是模糊信息和非结构化知识任务的复杂检索任务，那么和微软最近的GraphRAG相比有什么优势啊？

### ISSUE THREAD

**Issue by klenkiven** [qhjqhj00/MemoRAG#20]

**Comment by qhjqhj00** [comment]
您好，感谢您的提问。GraphRAG和MemoRAG期望解决的问题比较类似，技术途径有差别，各有优势。目前的阶段。GraphRAG比较依赖于API，我试用后发现至少得用GPT-4o才能保证效果。MemoRAG是model-based，我们在不断优化memory model的能力，将会提供更多的应用场景，并极大优化MemoRAG的效率！
