### ISSUE TITLE
How is memory token initialized/trained? Will the training code be available?

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [qhjqhj00/MemoRAG#21]
Thanks for the great work! I'm wondering how is the memory token initialized? 
Concretely, for the `x_1^{m}, x_2^{m},...x_k^{m}` below, how is it initialized? Also, are `x_1^{m}, x_2^{m},...x_k^{m}` trainable parameters?  For different contexts, do you need to retrain to get different `x_1^{m}, x_2^{m},...x_k^{m}` or are different contexts share the same memory tokens?
<img width="996" alt="Screenshot 2024-09-13 at 5 21 05 PM" src="https://github.com/user-attachments/assets/c05e64a6-cd71-4b73-836f-490b2ba9996a">

Lastly, will the training script be available? Thanks.

**Comment by qhjqhj00** [comment]
Thank you for your question. We will be releasing the training code soon. In the meantime, for details on memory token initialization, please refer to the .py scripts in the model directory.

**Comment by LiuXiaoxuanPKU** [comment]
> are `x_1^{m}, x_2^{m},...x_k^{m}` trainable parameters?

Just want to get some quick answer here:
1. Are memory tokens trainable?
2.  For different contexts, do you need to retrain to get different x_1^{m}, x_2^{m},...x_k^{m} or are different contexts share the same memory tokens?
Thanks!

**Comment by qhjqhj00** [comment]
1. yes, the memory tokens are trainable
2. the memory tokens x_1^{m}, x_2^{m},...x_k^{m} are summarized from recent normal tokens, so they are context-dependent.
