### ISSUE TITLE
Is it possible to use COLBERTv2 as a retrieval Model?

### ISSUE THREAD

**Issue by dibu28** [qhjqhj00/MemoRAG#25]
Is it possible to use COLBERTv2 from fastembed library as a retrieval Model?

Because for RAG I'm getting better results with COLBERTv2 then with BAAI/bge-m3 model.

**Comment by qhjqhj00** [comment]
We are considering adding more retrieval methods to MemoRAG, including ColBERT, though we cannot guarantee a specific release timeline. In the meantime, you are welcome to customize MemoRAG by integrating your own implementation.
