### ISSUE TITLE
LlamaForCausalLM.__init__() got an unexpected keyword argument 'beacon_ratio'

### ISSUE THREAD

**Issue by XinyuDu** [qhjqhj00/MemoRAG#26]
测试中文模型"shenzhi-wang/Llama3.1-8B-Chinese-Chat"的时候，报‘got an unexpected keyword argument 'beacon_ratio'的错误。

**Comment by XinyuDu** [comment]
升级最新代码解决了。

**Comment by jvel07** [comment]
@XinyuDu did you receive the error 
`pipe.memorize(small_part, save_dir="constitution/", print_stats=True)`
when loading a different model than TommyChien/memorag-qwen2-7b-inst?
Did you try llama3 official HF model?
