### ISSUE TITLE
Repo Works only with TommyChien/memorag-qwen2-7b-inst? Problems with Gated HF Models like Llama3

### ISSUE THREAD

**Issue by jvel07** [qhjqhj00/MemoRAG#29]
@qhjqhj00 the repo looks promising!

I am getting a HF auth error. I already got granted access to llama3.1 and I am using my HF token like below. I am using the 0.1.3 version.
```
from memorag import MemoRAG
from huggingface_hub import login

login(token=token_here, add_to_git_credential=True)

pipe = MemoRAG(
    mem_model_name_or_path="meta-llama/Meta-Llama-3.1-8B",
    ret_model_name_or_path="BAAI/bge-m3",
    beacon_ratio=16,
    load_in_4bit=True,
    enable_flash_attn=True,
    access_token='token_here'
)
```

However, I get this error (again, I already got access granted --my token has read-only properties):
```
Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3.1-8B/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3.1-8B is restricted. You must have access to it and be authenticated to access it. Please log in.
```

I decided to download the model directly from HF (using the same token) and it had no issue:
```
model_name = "meta-llama/Meta-Llama-3.1-8B"
local_dir = "./meta-llama-3.1-8b"
snapshot_download(repo_id=model_name, local_dir=local_dir, token=same_token)
```

However, I am not able to use this model as when I do:
`pipe.memorize(small_part, save_dir="constitution/", print_stats=True)`
I get the error:
`AttributeError: 'LlamaForCausalLM' object has no attribute 'memory'`

It just works with the `TommyChien/memorag-qwen2-7b-inst` or what am I missing here?

**Comment by jvel07** [comment]
The issue is here, the argument should be `access_token` instead of `token` in `memorag.py`:

```
        self.model_kwargs = {
            "cache_dir": cache_dir,
            # "token": access_token,
            "access_token": access_token,
            "device_map": {"": device},
            "attn_implementation": attn_implementation,
            "torch_dtype": torch.bfloat16,
            "trust_remote_code": True,
        }
```
same for the tokenizer kwargs...
Hope that helps!

**Comment by jvel07** [comment]
@qhjqhj00 had to reopen because: (btw, now I am using the latest memorag version)
```
ValueError: Cannot use apply_chat_template() because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template
```

**Comment by qhjqhj00** [comment]
thanks for your comment, we would fix it in the next version!
