### ISSUE TITLE
Could you please open the Demo Codes ?

### ISSUE THREAD

**Issue by BigdataEdison** [qhjqhj00/MemoRAG#31]
Hello, we would like to run this prototype interface. Can the source code be opened up ？ Thank  you  very much，We hope to discuss relevant issues together

**Comment by BigdataEdison** [comment]
@qhjqhj00

**Comment by qhjqhj00** [comment]
The demo code examples currently rely on the previous raw project code. I plan to find some time to update them to align with the tools in this repository and aim to release the updated version in October.

**Comment by BigdataEdison** [comment]
你的来信我已收到，我会尽快回复你。

**Comment by BigdataEdison** [comment]
> The demo code examples currently rely on the previous raw project code. I plan to find some time to update them to align with the tools in this repository and aim to release the updated version in October.

Thks
