### ISSUE TITLE
没有关于km、qm的实现

### ISSUE THREAD

**Issue by hemintang** [qhjqhj00/MemoRAG#33]
代码没有论文中关于km、qm的好像都没有实现
<img width="618" alt="image" src="https://github.com/user-attachments/assets/1d8fafbe-c0e9-4823-89f6-d19771b4c12b">

**Comment by qhjqhj00** [comment]
please refer to https://huggingface.co/TommyChien/memorag-qwen2-7b-inst/blob/main/modeling_beacon.py
