### ISSUE TITLE
论文中Qmem Kmem Vmem 的实现是？

### ISSUE THREAD

**Issue by aspatic** [qhjqhj00/MemoRAG#47]
是否是和TransformerXL  (Dai et al., 2019) 当中的一样在新增加的token上循环更新？
Segment-Level Recurrence？

**Comment by aspatic** [comment]
看不懂huggingface上的代码beacon部分，没注释

**Comment by qhjqhj00** [comment]
和TransformerXL不一样。之后代码我更新下注释。
