### ISSUE TITLE
多卡 或者别的什么方式实现68k文本记忆

### ISSUE THREAD

**Issue by aspatic** [qhjqhj00/MemoRAG#49]
我尝试在这个哈利波特的文本上复现 这个“When using the NVIDIA T4 16GiB, MemoRAG can handle databases with a context length of 68K tokens.”
但是不知为何按照example给的pipe=memorag(...)，连5k的文本memorize都爆显存。看起来mem-qwen大概8g,然后bge的检索模型2g，剩下的应该是够68k的上下文的？
麻烦指教这个16G记忆68k上下文问答端到端的setup是什么。或者我怎么把这个代码用上多卡，这也算可以实现68k上下文的。

**Comment by qhjqhj00** [comment]
可以参考这个notebook:
https://colab.research.google.com/drive/1fPMXKyi4AwWSBkC7Xr5vBdpPpx9gDeFX?usp=sharing
