### ISSUE TITLE
Do you want to extract an abstract of vector database 

### ISSUE THREAD

**Issue by zc277584121** [qhjqhj00/MemoRAG#6]
hello there, we think memoRAG is a great and inspireful work.  I noticed that you use faissIndex in the code. We want to contribute the capabilities of the vector database e.g. Milvus to this repo, that is, extract an abstract class `vectorIndex`, and then faiss and other vector databases inherit it. Do you think it is feasible? If so, I am very happy to cooperate and contribute code.

**Comment by qhjqhj00** [comment]
Thank you for your suggestions. We are currently discussing the TODO list for MemoRAG, and I find your suggestion particularly intriguing. I will discuss it with other members!
