### ISSUE TITLE
update pkg

### ISSUE THREAD

**Issue by tqangxl** [qhjqhj00/MemoRAG#8]
torch: 2.4.1
transformers 4.44.2
deepspeed-0.15.1 for Windows：
https://www.piwheels.org/simple/deepspeed/deepspeed-0.15.1-py3-none-any.whl
from https://www.piwheels.org/project/deepspeed/

**add rouge-chinese？？**
add seaborn ref pkg：
    torchvision
    ultralytics

**Comment by qhjqhj00** [comment]
thanks for your feedback, we will modify these soon!

**Comment by tqangxl** [comment]
> thanks for your feedback, we will modify these soon!
https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3
这个有0.3的版本了
能加一个Windows下运行的eval.bat或者在powerShell下运行的eval.ps1文件吗？

**Comment by tqangxl** [comment]
pip install git+https://github.com/huggingface/transformers
安装最新的含Qwen2VLForConditionalGeneration的
