### ISSUE TITLE
模型传一份到modelscope吧

### ISSUE THREAD

**Issue by tqangxl** [qhjqhj00/MemoRAG#9]
HF实在太慢了
modelscope的速度
![1726055177214](https://github.com/user-attachments/assets/ad0e82d4-6d15-4631-843b-1feeff39f96d)
![image](https://github.com/user-attachments/assets/bb1d311f-d38a-440e-a058-5cdfd35a39b4)

INFO:root:Building punc model.
INFO:root:download models from model hub: ms
2024-09-11 17:23:30,044 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-09-11 17:23:30,044 - modelscope - INFO - Use user-specified model revision: master
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 812/812 [00:00<00:00, 956B/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 450/450 [00:00<00:00, 1.17kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39.6M/39.6M [00:12<00:00, 3.25MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10.8M/10.8M [00:03<00:00, 3.62MB/s]
Downloading:   9%|█████████▋                                                                                                   | 95.0M/1.05G [00:19<03:19, 5.14MB/s]

**Comment by qhjqhj00** [comment]
您可以尝试:
```bash
export HF_ENDPOINT=https://hf-mirror.com
```
来加速hf model的下载。
